### DISCUSSION TITLE
Project Selector in UI Not Showing Project Names

### DISCUSSION THREAD

**Discussion by ahmdsye** [feast-dev/feast#5376] [Q&A]
Running Feast in GKE, encountered an issue with the UI project selector. While my deployment correctly recognizes multiple projects in the backend, the UI dropdown only displays the generic label "Project" instead of showing actual project names. 
![image](https://github.com/user-attachments/assets/19e0b9a0-47ec-4177-b313-e48da045c878)

Verified that multiple projects exist by running `feast projects list` from within the pod:
```
NAME                        DESCRIPTION                                  
Proj A   A project to perform estimation for A restaurant  {}
Proj B  A project to perform estimation for B restaurant  {}
```

thought it bcs my feature store.yaml using var:
```
project: Proj A
registry:
  registry_type: sql
  path: postgresql+psycopg://postgres:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DB}
```

but after fetch secrets in feature store deployment also doesnt work:
```
ui: 
      env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: feast-config
              key: pg_pass
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: feast-config
              key: pg_host
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: feast-config
              key: pg_db
      logLevel: debug
```

anything i missed out, requires help 🙏
