### ISSUE TITLE
Where do I setup the authentication for big query in feast

### ISSUE THREAD

**Issue by Adedolapo-Akin** [feast-dev/feast#1313]
### Specifications

- Version:
- 0.8
- Platform:
-GCP
- Subsystem:

**Comment by jklegar** [comment]
hey @Adedolapo-Akin, thanks for trying out Feast. You should need to setup authentication for BigQuery in two places - the feast-jupyter pod and Dataproc (given you're on GCP). For feast-jupyter, you should create a k8s secret and then point the gcpServiceAccount helm values to it - see https://github.com/feast-dev/feast/tree/v0.8-branch/infra/charts/feast/charts/feast-jupyter for the helm configuration and https://github.com/feast-dev/feast/tree/v0.9-branch/infra/terraform/gcp for an example (specifically the feast.tf and iam.tf files). For Dataproc, you can make sure it has access to BigQuery from within the GCP console. Let me know if you run into anything - our documentation is definitely sparse in this area.

**Comment by Adedolapo-Akin** [comment]
hi @jklegar  thanks
I am new to k8s so its a bit of upskilling exercise for me.

For jupyter, I added the service account details to the values.yaml file but I get the below error after installing(helm install) the pods.

 kubectl describe pod feast-release-ade-feast-jupyter-7cdcd85f64

  Unable to attach or mount volumes: unmounted volumes=[feast-release-ade-feast-jupyter-gcp-service-account], unattached volumes=[default-token-wd4sc feast-release-ade-feast-jupyter-gcp-service-account]: timed out waiting for the condition

  Unable to attach or mount volumes: unmounted volumes=[feast-release-ade-feast-jupyter-gcp-service-account], unattached volumes=[default-token-wd4sc feast-release-ade-feast-jupyter-gcp-service-account]: timed out waiting for the condition

MountVolume.SetUp failed for volume "feast-release-ade-feast-jupyter-gcp-service-account" : secret "feast-store" not found

**Comment by Adedolapo-Akin** [comment]
@jklegar 
kindly disregard the previous message.
I was able to resolve the error message.

I am busy testing my connection to Big Query. I will update you on the result.

Regards,

**Comment by Adedolapo-Akin** [comment]
@jklegar 

I get the below error message in  jupyter notebook
when I run the below

job = client.get_historical_features(
    feature_refs=[
        "driver_statistics_bq:avg_daily_trips",
        "driver_statistics_bq:conv_rate",
        "driver_statistics_bq:acc_rate",
        "driver_statistics_bq:trips_today"
    ],
    entity_source=bq_entities_with_timestamp
)
Error

DefaultCredentialsError: File /etc/secrets/google/gcpServiceAccount.existingSecret.key=concise-hue-297815-449eca64adcd.json was not found.

**Comment by jklegar** [comment]
hey @Adedolapo-Akin, creating the secret should look something like `kubectl create secret generic feast-store --from-file=./credentials.json` where the `./credentials.json` part is the json file you get when you create a GCP service account. Then in helm, you'll want
```
gcpServiceAccount:
  # gcpServiceAccount.enabled -- Flag to use [service account](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) JSON key
  enabled: true
  existingSecret:
    # gcpServiceAccount.existingSecret.name -- Name of the existing secret containing the service account
    name: feast-store
    # gcpServiceAccount.existingSecret.key -- Key in the secret data (file name of the service account)
    key: credentials.json
```
where if the json file you got when creating a GCP service account has a different name you should replace `credentials.json` in the above yaml with that name.

Let me know if that works :)
