### ISSUE TITLE
CLI `feast materialize` does not work with custom providers

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1589]
## Expected Behavior 
This should work as it works with `feast apply`

## Current Behavior
You get a `ModuleNotFoundError`
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/18557047/119858530-8d73e080-bee2-11eb-83e3-cae866b5a8be.png">

## Steps to reproduce
I have my own custom provider
```
# feature_store.yaml
project: local
registry: tmp/registry.db
provider: pano.provider.LocalProvider
offline_store:
    type: bigquery
online_store:
    type: sqlite
    path: tmp/database.db
```
- `feast apply`  works as expected
- `feast materialize-incremental` does not because it cannot find my "pano" module

### Specifications

- Version: feast 0.10.5
- Platform: Mac
- Subsystem:

## Possible Solution

They both use [get_provider() from infra/provider.py](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/provider.py#L141)

The `apply` method in the CLI will do 
```
os.chdir(repo_path)
sys.path.append("")
...
infra_provider = get_provider(repo_config, repo_path)
```

The `materialize-incremental` method of the CLI will do
```
provider = self._get_provider()
# That will return `return get_provider(self.config, self.repo_path)`
```

So the difference is that the FeatureStore does not append the current directory in the sys path
