### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by tiru1930** [feast-dev/feast#1639]
```
(_Metadatum(key='user-agent', value='grpc-python/1.31.0 grpc-c/11.0.0 (linux; chttp2)'),))
jobservice_1         | 2021-06-11 12:07:13,154 [ERROR] grpc._server: Exception calling application: invalid literal for int() with base 10: ''
jobservice_1         | Traceback (most recent call last):
jobservice_1         |   File "/opt/conda/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
jobservice_1         |     response_or_iterator = behavior(argument, context)
jobservice_1         |   File "/app/python/feast_spark/job_service.py", line 134, in StartOfflineToOnlineIngestionJob
jobservice_1         |     job = start_offline_to_online_ingestion(
jobservice_1         |   File "/app/python/feast_spark/pyspark/launcher.py", line 276, in start_offline_to_online_ingestion
jobservice_1         |     and client.config.getint(opt.REDIS_PORT),
jobservice_1         |   File "/opt/conda/lib/python3.8/site-packages/feast/config.py", line 164, in getint
jobservice_1         |     return self._get(option, default, self._config.getint)
jobservice_1         |   File "/opt/conda/lib/python3.8/site-packages/feast/config.py", line 120, in _get
jobservice_1         |     return get_method(
jobservice_1         |   File "/opt/conda/lib/python3.8/configparser.py", line 818, in getint
jobservice_1         |     return self._get_conv(section, option, int, raw=raw, vars=vars,
jobservice_1         |   File "/opt/conda/lib/python3.8/configparser.py", line 808, in _get_conv
jobservice_1         |     return self._get(section, conv, option, raw=raw, vars=vars,
jobservice_1         |   File "/opt/conda/lib/python3.8/configparser.py", line 803, in _get
jobservice_1         |     return conv(self.get(section, option, **kwargs))
jobservice_1         | ValueError: invalid literal for int() with base 10: ''
igt_lingspam_jupyter |[I 2021-06-11 12:08:48.899 ServerApp] Saving file at /notebooks/feast.ipynb


````

```
  notebook:
    build:
      context: .
      dockerfile: ./dockerfiles/notebook.Dockerfile
    image: igt-lingspam/jupyter:latest
    container_name: igt_lingspam_jupyter
    volumes:
      - ./data:/experiments/data
      - ./notebooks:/experiments/notebooks
      - ${GCP_SERVICE_ACCOUNT}:/etc/gcloud/service-accounts/key.json
      - $PWD:/shared
    depends_on:
      - core
    entrypoint: "bash -c 'jupyter lab --no-browser --ip=0.0.0.0 --port=8877 --allow-root'"
    environment:
      FEAST_CORE_URL: core:6565
      FEAST_SERVING_URL: online_serving:6566
      FEAST_SPARK_LAUNCHER: standalone
      FEAST_SPARK_STANDALONE_MASTER: local
      FEAST_SPARK_HOME: /usr/local/spark
      FEAST_SPARK_STAGING_LOCATION: file:///shared/staging
      FEAST_HISTORICAL_FEATURE_OUTPUT_LOCATION: file:///shared/historical_feature_output
      FEAST_HISTORICAL_FEATURE_OUTPUT_FORMAT: parquet
      FEAST_REDIS_HOST: redis
      FEAST_REDIS_PORT: 6379
      GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/service-accounts/key.json
    ports:
      - "8877:8877"
````
- Version:
- Platform:
- Subsystem:
