### ISSUE TITLE
FeatureService should support "description" as first class named-value argument as Entity does

### ISSUE THREAD

**Issue by dmatrix** [feast-dev/feast#1770]
## Expected Behavior 
...
```
# Define your feature service and the features it will serve
driver_fs = FeatureService(name="driver_ranking_fv_svc",
                           features=[driver_hourly_stats_view],
                           description="Used for training an ElasticNetCV model"})
```
```
feast feature-services describe driver_ranking_fv_svc
spec:
  name: driver_ranking_fv_svc
  features:
  - featureViewName: driver_hourly_stats
    featureColumns:
    - name: conv_rate
      valueType: FLOAT
    - name: acc_rate
      valueType: FLOAT
    - name: avg_daily_trips
      valueType: INT64
description: Used for training an ElasticNetCV model
meta: {}
```
Extend the argument list in the [FeatureService ](https://github.com/feast-dev/feast/blob/7dff49a194a25a62927c1ee7022caf0651f68f38/sdk/python/feast/feature_service.py#L24)to support `description=None` as default
## Current Behavior

```
# Define your feature service and the features it will serve
driver_fs = FeatureService(name="driver_ranking_fv_svc",
                           features=[driver_hourly_stats_view],
                           tags={"description": "Used for training an ElasticNetCV model"})
```
Then query the FS from the cli

```
feast feature-services describe driver_ranking_fv_svc
spec:
  name: driver_ranking_fv_svc
  features:
  - featureViewName: driver_hourly_stats
    featureColumns:
    - name: conv_rate
      valueType: FLOAT
    - name: acc_rate
      valueType: FLOAT
    - name: avg_daily_trips
      valueType: INT64
  tags:
    description: Used for training an ElasticNetCV model
meta: {}
```
## Steps to reproduce

Follow the steps above in the current behavior

### Specifications

- Version: v0.12v
