### ISSUE TITLE
s3_staging_location and iam_role fields

### ISSUE THREAD

**Issue by fcas** [feast-dev/feast#1857]
**Is your feature request related to a problem? Please describe.**

_s3_staging_location field_

I would like to understand why it was associated a deployment environment name in this variable name: `s3_staging_location`. It's makes some confusion when we try to understand how the things works behind the scenes. Besides, this field name can lead to fake semantics. For exemple, in our context we have the `s3_staging_location` with a production location value.

_iam_role field_

Why the iam_role field is exclusive to the offline feature store scope? In this way is not possible to reuse the role used to the offline feature store.

**Describe the solution you'd like**
```
offline_store:
    type: redshift
    region: us-west-2
    cluster_id: ******
    database: ******
    user: ******
    s3_staging_location: ******
    iam_role: arn:aws:iam::account_id_1:role/role_1
online_store:
    type: dynamodb
    region: us-east-1
    iam_role: arn:aws:iam::account_id:role/role_1
```

**Describe alternatives you've considered**
We created a role that was not possible to reuse in the online store context. So, we increase the permissions to the role (role_2) used by the aws-vault: 
 ```
 aws-vault exec role_2
 ```   

**Additional context**
The additional permission was restricted to one user group, we can't use the same solution for other user groups.

**Comment by felixwang9817** [comment]
@fcas,

The `s3_staging_location` is named `staging` because it is only used temporarily for staging data that is required for the Redshift offline store's functionality, such as doing point-in-time joins. The `staging` here does not mean that it cannot be used for production purposes. Hopefully this makes sense.

I'm not quite sure what you mean regarding the `iam_role` field. Why exactly do you want an `iam_role` for the online store?

**Comment by fcas** [comment]
Thanks for the explanation! I need the `iam_role` just to assign a role with these permissions: https://docs.feast.dev/reference/online-stores/dynamodb

**Comment by woop** [comment]
@fcas are you asking for us to add support for specifying a role for DynamoDB (which is distinct from the offline store)? I think that should be a pretty easy change.

**Comment by woop** [comment]
I think we should maybe move away from specifying the role and instead use profiles (like [](https://docs.getdbt.com/reference/warehouse-profiles/redshift-profile) does)

**Comment by fcas** [comment]
@woop the role is the same to online and offline store. 

However, during run time we have distinct roles being used:

```
aws-vault exec profile (that uses role_2) -- pipenv run feast apply
# 1 - offline store -> assumes role 1 specified in the feature_store.yaml, 
# 2 - online store assumes role 2 specified in the ~/.aws/config
```

_feature_store.yaml_
```
offline_store:
    type: redshift
    region: us-west-2
    cluster_id: ******
    database: ******
    user: ******
    s3_staging_location: ******
    iam_role: arn:aws:iam::account_id:role/role_1
online_store:
    type: dynamodb
    region: us-east-1
```

_~/.aws/config_
```
...

[profile ***]
sso_start_url = ***
sso_region = us-east-1
sso_account_id = ****
sso_role_name = role_2
region = us-east-1
```
