### ISSUE TITLE
feast alpha enable command messes up feature_store.yaml

### ISSUE THREAD

**Issue by felixwang9817** [feast-dev/feast#1938]
## Expected Behavior

Calling `feast alpha enable python_feature_server` should add
```
flags:
  alpha_features: true
  python_feature_server: true
```
to `feature_store.yaml`.

## Current Behavior

Instead, it changes
```
project: sharing_sculpin
registry: data/registry.db
provider: local
online_store:
    path: data/online_store.db
```
to
```
project: sharing_sculpin
provider: local
online_store:
  path: data/online_store.db
offline_store: {}
flags:
  alpha_features: true
  python_feature_server: true
```
This still works due to the Pydantic defaults, but can be very confusing for users.

Edit: in some cases, it actually doesn't preserve the same effect. For example, the command changes
```
project: sharing_sculpin
provider: local
online_store:
  type: redis
offline_store: {}
flags:
  alpha_features: true
  python_feature_server: true
```
to
```
project: sharing_sculpin
provider: local
online_store: {}
offline_store: {}
flags:
  alpha_features: true
  python_feature_server: true
```
which is incorrect since the `online_store` no longer has type `redis`.

## Steps to reproduce

Call `feast init` to create a new `feature_repo`. Then call `feast alpha enable python_feature_server`, and inspect `feature_store.yaml` before and after this command.

### Specifications

- Version:
- Platform:
- Subsystem:
