### ISSUE TITLE
Redis Cluster materialization error

### ISSUE THREAD

**Issue by qooba** [feast-dev/feast#1967]
## Expected Behavior 
Materialization for Redis Cluster works 

## Current Behavior
During materialization Feast use Redis client instead of RedisCluster client

## Steps to reproduce
configure redis cluster 
```
project: my_feature_repo
registry: data/registry.db
provider: local
online_store:
  type: redis
  redis_type: redis_cluster
  connection_string: "redis1:6379,redis2:6379,ssl=true,password=my_password"
```
try to materialize

### Specifications

- Version: 0.14.0
- Platform: python 3.7
- Subsystem: linux (anaconda3 docker image)

## Possible Solution
correct _get_client method in redis.py l. 124
