### ISSUE TITLE
`feast apply` broken with 0.15.* if the registry already exists

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#2086]
## Expected Behavior 
Running `feast apply` twice in a row should work as expected

## Current Behavior
The second time we run `feast apply`, it will break with feast v0.15.*

## Steps to reproduce
- install Feast 0.15.1
- Add a local config
```yaml
project: local
registry: tmp/registry.db
provider: local
offline_store:
    type: bigquery
    dataset: scratch
online_store:
    type: sqlite
    path: tmp/database.db
```
- `feast apply` ✅ if the registry does not exist
- `feast apply` 🔴 
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/18557047/143126061-aac2b200-d087-490d-afae-e4e738bcdf4b.png">
From Slack
> And interestingly, it does not always fail on the same FeatureView being applied
> And I can successfully print feature_view_proto.spec.entities right before it fails

### Specifications

- Version:
- Platform:
- Subsystem:
