### ISSUE TITLE
feature-server-java not work

### ISSUE THREAD

**Issue by hsz1273327** [feast-dev/feast#2162]
I try to use docker image `feastdev/feature-server-java:0.16.1`,but it seems not work.

it try to query same feature, `feastdev/feature-server-java:0.16.1` can not find it but `feast serve` works.

+ config

    ```yml
    feast:
      registry: "/data/features/registry.db"
      active_store: online
      stores:
        - name: online
          type: REDIS
          config:
            host: 172.16.1.105
            port: 7007
            db: 7
            password: xxxxxxxxx
          subscriptions:
            - name: "*"
              project: "*"
    ```

+ registry is on nfs,and use volumes to bind in container

+ query feature-server-java (publish port in docker: " 6567:6566")

    + query
      
        ```bash
        ./grpcurl -plaintext -d '{"project": "feature_repo","features": [ {"feature_table":"user_feature", "name": "gender"}], "entity_rows": [{ "fields": { "user_id": {"string_val":"204061539"} }}]}' localhost:6567 feast.serving.ServingService/GetOnlineFeaturesV2
        ```
    + response
        ```json
        {
          "field_values": [
            {
              "fields": {
                "user_feature:gender": {
                  
                },
                "user_id": {
                  "string_val": "204061539"
                }
              },
              "statuses": {
                "user_feature:gender": "NOT_FOUND",
                "user_id": "PRESENT"
              }
            }
          ]
        }
        ```

+ query the http server run by `feast serve` (port 6566)

    + query
        ```bash
        curl -X POST \
          "http://localhost:6566/get-online-features" \
          -d '{
            "features": [
              "user_feature:gender"
            ],
            "entities": {
              "user_id": ["204061539"]
            }
          }'
        ```
    + response
        ```json
        {"field_values":[{"fields":{"user_id":"204061539","gender":2},"statuses":{"gender":"PRESENT","user_id":"PRESENT"}}]}
        ```

**Comment by pyalex** [comment]
Hi @hsz1273327, can you please also provide your `feature_store.yaml`?

**Comment by Lugoues** [comment]
I'm having this exact same problem.

Here is my `feature_store.yaml` if that helps. Let me know if there is anything else I can do to assist.
```yaml
registry: gs://my_proj/feast/registry.db
project: my_proj
provider: gcp
online_store:
  type: redis
  redis_type: redis
  connection_string: xxx.xxx.xxx.xxx:6379
offline_store:
  type: bigquery
  dataset: my_proj_featurestore_offline
  project_id: my_proj
  location: US
flags:
  alpha_features: true
  on_demand_transforms: true
 ```

**Comment by pyalex** [comment]
@Lugoues Please provide full information:
* your application.yml (java server config). Make sure that "project" matches in `feature_store.yaml` and `application.yml`
* example of working request (against Python server)
* example of not working request (against Java server)

**Comment by pyalex** [comment]
Fixed by https://github.com/feast-dev/feast/pull/2264

**Comment by hsz1273327** [comment]
It seems not fix yet.  I update feast to 0.18.1 and seems nothing changes.

+ feature_store.yaml
```yml
registry: registry.db   
project: feature_repo
provider: local
online_store:
  type: redis
  connection_string: "172.16.1.105:7007,db=7,password=0iY87blaERqARYie"
offline_store:
  type: file
flags:
  alpha_features: true
  direct_ingest_to_online_store: true
```

+ application_override.yml

```yml
feast:
    project: "feature_repo"
    registry: "/data/features/registry.db"
    activeStore: online
    stores:
        - name: online
          type: REDIS
          config: 
              host: 172.16.1.105
              port: 7007
              db: 7
              password: 0iY87blaERqARYie
```

+ http query & response

```bash
root@93c0769466ad:/# curl -X POST \
>   "http://feature-serve:6566/get-online-features" \
>   -d '{
>     "full_feature_names":true,
>     "features": [
>       "user_featureV1:gender",
>       "user_featureV1:channel_weight"
>     ],
>     "entities": {
>       "user_id": ["54370861"]
>     }
>   }'

{"metadata":{"feature_names":["user_id","user_featureV1__gender","user_featureV1__channel_weight"]},"results":[{"values":["54370861",0,92.0],"statuses":["PRESENT","PRESENT","PRESENT"],"event_timestamps":["1970-01-01T00:00:00Z","2022-03-09T09:00:00Z","2022-03-09T09:00:00Z"]}]}
```

+ grpc query & response

```bash
$ ./grpcurl -plaintext -d @ localhost:6566 feast.serving.ServingService/GetOnlineFeatures < oldfeast.json
{
  "metadata": {
    "feature_names": {
      "val": [
        "user_featureV1:gender",
        "user_featureV1:channel_weight"
      ]
    }
  },
  "results": [
    {
      "values": [
        {
          
        }
      ],
      "statuses": [
        "NOT_FOUND"
      ],
      "event_timestamps": [
        "1970-01-01T00:00:00Z"
      ]
    },
    {
      "values": [
        {
          
        }
      ],
      "statuses": [
        "NOT_FOUND"
      ],
      "event_timestamps": [
        "1970-01-01T00:00:00Z"
      ]
    }
  ]
}
```

+ `oldfeast.json`

```json
{
    "features": {
        "val": [
            "user_featureV1:gender",
            "user_featureV1:channel_weight"
        ]
    },
    "entities": {
        "user_id": {
            "val": [
                {
                    "string_val": "204194401"
                }
            ]
        }
    },
    "full_feature_names": true
}
```
