### ISSUE TITLE
feast.errors.FeatureViewNotFoundException on kubernetes pod.

### ISSUE THREAD

**Issue by mdrijwan123** [feast-dev/feast#2855]
This question may be for a recommendation or suggestion for proper feast deployment.
I am observing strange behaviour for feast server deployed in Kubernetes as compared to local.
I have configured Azure blob storage for the feast server and configured cache_ttl_seconds as 60 seconds. 
The strange scenario is:
1) If I delete the registry from blob storage, both local and Kubernetes pod registry is unaccessible.
2) If I delete a feature to view from registry us fs.delete_feature_view('test_vw'), in local it reflected after ttl time but its keeps showing feature view not found in Kubernetes.
I deleted the registry and run feast apply in both then also the same scenario in local its everything fine but in Kubernetes same error:
Feature view test_vw does not exist.
It seems that Kubernetes is able to observe the registry.db file but not able to read any views, but in local it's running perfectly.
## Expected Behavior 

It would be great if some exact message we should get if there is any inconsistency observed in reading registry.db or not, though it's better to be handled in client-side it solves a lot of confusion.

My feature_store.yaml file :
```
project: Feature_spark    
registry:    
    registry_store_type: feast_azure_provider.registry_store.AzBlobRegistryStore    
    path: ${REGISTRY_PATH}    
    cache_ttl_seconds: 60    
provider: local    
online_store:    
    type: redis    
    redis_type: redis    
    connection_string: ${REDIS_CONN}    
go_feature_server: True
```

## Current Behavior
Not able to read feature view consistently in Kubernetes environment.

### Specifications

- Version: feast: feast[redis]==0.19.4
- Platform: ubuntu

I am a little confused if the issue is related to:
1) The deployment where we have created config map of feature_store.yaml and replaced the value at run time.
2) The blob key is being used, but in local it's working fine.

Or how feast processes the feature Store object in memory to manage the registry store and other stuff.
Any help or recommendation is appreciated to resolve this type of scenario if anybody has encountered or even thought of it as a possible issue in production.
