### ISSUE TITLE
Introduce profile selector for AWS credentials

### ISSUE THREAD

**Issue by antonum** [feast-dev/feast#2874]
Users might have multiple AWS accounts/credentials, stored in .aws/credentials. In the AWS command line or Terraform one can easily specify which one to use at any given time.

```
aws s3 ls --profile non-default-profile
```
Or in TF:
```
provider "aws" {
  profile  = "non-default-profile"
}
```

Feast today would always use the `default` profile. A potential workaround involves defining `AWS_PROFILE` env. variable.

This feature request proposes an explicit profile definition for Feast in feature_store.yaml, mimicking the terraform syntax.

Example:
```
project: my_feature_repo
registry: data/registry.db
provider: aws
  profile: non-default-profile # <== proposed optional profile selector
online_store:
  type: dynamodb
  region: us-west-2
...
```
