### ISSUE TITLE
First online feature request taking much time than other sequential request.

### ISSUE THREAD

**Issue by mdrijwan123** [feast-dev/feast#2952]
I am using kserve for model inference and inside the code I am calling get_online_features from redis online store, I am not using feature server because python feature server is not meeting with out latency requirement. But even after using get_online_features first request is taking more time than second always, so the latency is inconsistent. 
Like:

```
from feast import FeatureStore
fs = FeatureStore("feast_repo/")

def preprocess(self, inputs: Dict) -> Dict:
    t1 = time.time()
    online_product_data = self.fs.get_online_features(
                                    features = self.product_feature_refs,
                                    entity_rows = self.product_enities)
    t2 = time.time()
    online_user_data = self.fs.get_online_features(
                                    features = self.user_feature_refs,
                                    entity_rows = self.user_entities)
    t3 = time.time()
    logging.info("product time %s",t2-t1)
    logging.info("user time %s",t2-t1)
```

I am getting around 300 millisecond from product data and 12-50ms with user data. If I shuffle the user and product then user taking more than 300ms and product take around 80ms. overall latency is always increasing, due to this. The feature_store.yaml I am using is:

```
project: Feature_spark
registry: 
    registry_store_type: feast_azure_blob_connect.registry_store.AzBlobRegistryStore
    path: ${REGISTRY_PATH}
    cache_ttl_seconds: 60
provider: local
offline_store:
    type: spark
    spark_conf:
        spark.master: "local[*]"
        spark.app.name: "feast_offline"
        spark.ui.enabled: "true"
        spark.executor.memory: "12g"
        spark.driver.memory: "12g"
        spark.memory.offHeap.size: "16g"
        spark.memory.offHeap.enabled: "true"
        spark.eventLog.enabled: "true"
        spark.sql.catalogImplementation: "hive"
        spark.sql.parser.quotedRegexColumnNames: "true"
        spark.sql.session.timeZone: "UTC"
online_store:
        type: redis
        redis_type: redis
        connection_string: ${REDIS_CONN}
go_feature_server: True
```
## Expected Behavior 

I should not get much difference and inconsistency every time I hit the two consecutive online request.

## Current Behavior
The first Redis online store call is taking much time then second one, and if I shuffle the view call then again first is taking much time.

### Specifications

- Version: 0.22.0
- Platform: Linux
- Subsystem:
