### ISSUE TITLE
Inject AWS credentials as part of environment variables

### ISSUE THREAD

**Issue by gcheoyh** [feast-dev/feast#3303]
## **Is your feature request related to a problem? Please describe.**

I am currently setting up Feast Feature Server using the [Helm chart](https://github.com/feast-dev/feast/tree/master/infra/charts/feast-feature-server), with DynamoDB as my online store.

However, I run into issues with authentication/access to DynamoDB as the chart does not provide a way to inject AWS credentials easily.

Currently, the workaround has been to download a local copy of the Helm chart and modify the deployment to inject credentials as environment variables.

## **Describe the solution you'd like**

Propose to allow the Helm chart to take in `aws_secret_access_key` and `aws_access_key_id` as values, which can then be injected dynamically during deployment. This can be done by adding the following environment variables in the [`deployment.yaml`](https://github.com/feast-dev/feast/blob/master/infra/charts/feast-feature-server/templates/deployment.yaml)

```
          env:
            - name: FEATURE_STORE_YAML_BASE64
              value: {{ .Values.feature_store_yaml_base64 }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws_access_key_id }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws_secret_access_key }}
```

## **Describe alternatives you've considered**

See the workaround as mentioned above. In the long-term, this doesn't seem sustainable since we will need to propagate any changes from the remote chart to our local copy.

## **Additional context**

NIL
