### ISSUE TITLE
incremental materialization process killed - (Snowflake offline store/batch materialization engine)

### ISSUE THREAD

**Issue by ethanbates-ez** [feast-dev/feast#3310]
## Expected Behavior 
- materialization succeeds or throws a verbose exception

## Current Behavior
- features are not fully loaded into the online store
- process Killed / Interrupted without raising an exception 
- No failed queries on Snowflake
...
```
Materializing 1 feature views to 2022-10-22 00:00:00+00:00 into the redis online store.

user_weekly_orders_view from 1749-01-07 18:56:05+00:00 to 2022-10-22 00:00:00+00:00:
Snowflake: Processing Materialization ResultSet Batch #1
100%|█████████████████████████████████████████████████████████| 1284/1284 [00:00<00:00, 2159.67it/s]
Snowflake: Processing Materialization ResultSet Batch #2
100%|█████████████████████████████████████████████████████████| 3910/3910 [00:00<00:00, 4340.19it/s]
Snowflake: Processing Materialization ResultSet Batch #3
100%|█████████████████████████████████████████████████████████| 7883/7883 [00:01<00:00, 4628.58it/s]
Snowflake: Processing Materialization ResultSet Batch #4
100%|███████████████████████████████████████████████████████| 15769/15769 [00:03<00:00, 5205.82it/s]
Snowflake: Processing Materialization ResultSet Batch #5
Killed
```

## Steps to reproduce
Plan/Apply:
```
# feast -c feast_features/ plan 
Created entity user
Created feature view user_weekly_orders_view
Created feature service test_model_v1

No changes to infrastructure
# feast -c feast_features/ apply
Created entity user
Created feature view user_weekly_orders_view
Created feature service test_model_v1

Deploying materialization functions for feast_features

Deploying infrastructure for user_weekly_orders_view
```
Config:
```
project: feast_features
provider: local
registry:
  registry_type: sql
  path: ${POSTGRES_URL}
offline_store:
    type: snowflake.offline
    account: <redacted>
    user: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    role: ${SNOWFLAKE_ROLE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    database: ${SNOWFLAKE_DATABASE}
    schema: ML_FEATURES
batch_engine:
    type: snowflake.engine
    account: <redacted>
    user: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    role: ${SNOWFLAKE_ROLE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    database: ${SNOWFLAKE_DATABASE}
    schema: ML_FEATURES
online_store:
  type: redis
  connection_string: ${REDIS_URL}
entity_key_serialization_version: 2

```

### Specifications

- Version: `Feast SDK Version: "feast 0.26.0"`
- Platform:
    - Docker/K8s.
    - AWS Elasticache Redis (Online Store)
    - AWS Postgres RDS (Registry)
    - Snowflake (Offline Store, Batch Materialization Engine)
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Possible Solution
- [Associated with the Snowflake Engine?](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/materialization/snowflake_engine.py#L439)
- Assumed this might be associated with the connection to the online store, but some keys are being loaded before the process is Killed unexpectedly
```
>>> redis_client = StrictRedis(host=host, port=6379)
>>> key_check = redis_client.keys()
>>> len(key_check)
28846
.... After teardown ...
>>> len(key_check)
0
```
