### ISSUE TITLE
Feast UI: URL scheme "postgresql" is not supported when specifying SQL registry in `projects-list.json`

### ISSUE THREAD

**Issue by TomSteenbergen** [feast-dev/feast#3974]
## Expected Behavior 

The UI created using a custom React app with a SQL registry shows the entities, feature views, etc. per project.

## Current Behavior

It is unclear how to specify the `registryPath` in your `projects-list.json` file. The structure of this file could definitely benefit from some more documentation. 

While the Feast UI does spin up and shows the project names and descriptions from the `projects-list.json` on the homepage, it does not load and visualize the corresponding Feast objects when clicking on one of these projects, even though the registry does contain that data (see screenshot). 

![image](https://github.com/feast-dev/feast/assets/41334387/7529816b-92aa-410c-a71b-2d28fc67b18b)

The browser console shows the following error:

```
Fetch API cannot load postgresql://postgres:test@db:5432/feast. URL scheme "postgresql" is not supported.
```

The part `postgresql://postgres:test@db:5432/feast` is the connection string to my SQL registry that I created through `docker-compose` and that I pass in `projects-list.json` under the `registryPath` key.

Is a SQL registry is not supported yet by the UI? Or did I format `registryPath` incorrectly? 

## Steps to reproduce

1. Follow steps from the [docs](https://docs.feast.dev/reference/alpha-web-ui#importing-as-a-module-to-integrate-with-an-existing-react-app) to create a React app.
2. Add your `projects-list.json` to the `public` directory. My file looked like this:

```json
{
  "projects": [
    {
      "name": "Project 1",
      "description": "Description 1.",
      "id": "project_1",
      "registryPath": "postgresql://postgres:test@db:5432/feast"
    },
    {
      "name": "Project 2",
      "description": "Description 2.",
      "id": "project_2",
      "registryPath": "postgresql://postgres:test@db:5432/feast"
    }
  ]
}
```

3. Start a Postgres database using the following `docker-compose.yml`
```yaml
version: "3"
services:
  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ~/feast_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=feast
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
networks:
  backend:
    driver: bridge

volumes:
  feast_postgres_data: null
```

4. Run `yarn start`.

### Specifications

- Version: 0.35.0
- Platform: MacOS
- Subsystem: Sonoma 14.2

## Possible Solution

More documentation on setting up the UI would be very much welcome.
