### ISSUE TITLE
Evaluate adding support for ML Metadata or alternative

### ISSUE THREAD

**Issue by franciscojavierarceo** [feast-dev/feast#4258]
**Is your feature request related to a problem? Please describe.**

We should consider adding support for ML Metadata

**Describe the solution you'd like**
https://github.com/google/ml-metadata

**Describe alternatives you've considered**
N/A

**Additional context**
Kubeflow uses this library and we probably should too but we should get feedback first.

**Comment by franciscojavierarceo** [comment]
Looks like @dmartinol did this here: https://github.com/dmartinol/feast-workshop-team-share/tree/main/feast_modelregistry

**Comment by dmartinol** [comment]
Not exactly the same, @franciscojavierarceo. The demo you are pointing to aims to use MR and Feast in the same pipeline, but there is no actual integration between the tools. It would be better to discuss what we want to achieve. Specifically, we should decide if we want to adopt ML Metadata as a registry type (data layer integration):
```yaml
registry:
  registry_type: ml-metadata
  path: _ML_METADATA_URL_
```
or, potentially even further 😲, adopt Model Registry itself:
```yaml
registry:
  registry_type: model-registry
  path: _MODEL_REGISTRY_URL_
```
