### ISSUE TITLE
feast ui root_path isn't working as expected

### ISSUE THREAD

**Issue by dean-n** [feast-dev/feast#4373]
## Expected Behavior 
After running `feast ui root_path=/test`, I thought I should be able to access the feast ui at localhost:8888/test.

## Current Behavior
The routing doesn't seem to work and is unable to get the registry configuration.

```
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:48274 - "GET /test/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:48274 - "GET /test HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:48274 - "GET /projects-list.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:48274 - "GET /test/registry HTTP/1.1" 404 Not Found
```

## Steps to reproduce
```
feast ui root_path=/test
curl localhost:8888/test
```

### Specifications

- Version: 0.39.1
- Platform: Linux
- Subsystem:

## Other
I haven't seen any documentation on the `root_path` feature, please let me know how to configure it correctly if I'm making a mistake.

**Comment by tokoko** [comment]
Hey, that's not what `root_path` means, you need to specify it only if instead of exposing feast UI directly to the users, you've decided to put it behind some sort of a load balancer under a specific path, for example if a load balancer is forwarding requests starting with `/test` to your feast ui server. In that scenario, you need to specify `/test` as a `root_path` in order for server calls coming from the browser to work correctly.

**Comment by dean-n** [comment]
Hi @tokoko, thank you for your quick response 👍 

I'm just trying to create a small local example, to replicate what I think we'll eventually deploy in my org.

I've setup an nginx reverse proxy:
```
server {
    listen 80; 
    server_name localhost;          

    location /test/ {              
        rewrite /test/(.*) /$1  break;    
        proxy_pass http://localhost:8888; 
    }
    location / {
        proxy_pass http://localhost:8888;
    }
}
```
My aim with the above was to replicate how it'll be deployed, accessible under a specific path.

Would I need to run my ui via `feast ui root_path=/test` with the above setup?

I've tried this, and get a 404:
![image](https://github.com/user-attachments/assets/f0e44cb2-2d34-4248-b151-04df8bd52815)

Please note: I added the second location block to successfully retrieve some style files e.g. `http://localhost/static/css/main.4b6d8029.css`

**Comment by tokoko** [comment]
sorry, I'm not familiar with the UI codebase, so mostly speculating here. The style files issue seems like a bug, looks like `root_path` is only used in [ui_server.py](https://github.com/feast-dev/feast/blob/v0.39-branch/sdk/python/feast/ui_server.py) to specify path for a `/registry` endpoint.

**Comment by js7309** [comment]
index.html page change path

```
    spec:
      containers:
      - name: feature-ui
        image: feastdev/feature-server:0.40.1
        pullPolicy: IfNotPresent
        command:
          - /bin/bash
          - '-c'
        args:
            - |
              sed -i "s|href=\"|href=\"$PUBLIC_URL|g" /usr/local/lib/python3.11/site-packages/feast/ui/build/index.html
              sed -i "s|src=\"|src=\"$PUBLIC_URL|g" /usr/local/lib/python3.11/site-packages/feast/ui/build/index.html
              sed -i "s|/projects-list.json|${PUBLIC_URL}/projects-list.json|g" /usr/local/lib/python3.11/site-packages/feast/ui/build/static/js/main.2ebff4ed.js
              feast ui -h 0.0.0.0 --root_path ${PUBLIC_URL}
        env:
          - name: PUBLIC_URL
            value: /app
```
