### ISSUE TITLE
Add support for a local file-based datasource in remote Feature Server (online, offline, registry) when deployed using Podman/Docker locally

### ISSUE THREAD

**Issue by redhatHameed** [feast-dev/feast#4514]
## Expected Behavior 
Supporting Feast installation using [Podman](https://podman.io/) or Docker for setting up Feast remote components on local environments. And creating an example like the [quick start](https://docs.feast.dev/getting-started/quickstart) but using a [local file-based datasource](https://docs.feast.dev/reference/providers/local). The FileBase datasource can be mounted to the container, and access the data using that mount path and Path can be configured feature_store.yaml file according to mount path. 

```
project: my_project
# By default, the registry is a file (but can be turned into a more scalable SQL-backed registry)
registry: data/registry.db
# The provider primarily specifies default offline / online stores & storing the registry in a given cloud
provider: local
online_store:
    type: sqlite
    path: data/online_store.db
entity_key_serialization_version: 2
```

## Current Behavior

Currently there is missing steps how to configure Feast on Podman or using docker for remote server and how to perform `feast apply`

### Specifications

- Version: 0.40
- Platform: podman/docker
- Subsystem:

## Possible Solution
Create the documentation and examples which covers how to configure run Feast remote server locally using Podman
