### ISSUE TITLE
Feast create empty online table when FeatureView attribute online=False

### ISSUE THREAD

**Issue by SuperBo** [feast-dev/feast#4616]
## Expected Behavior 

Feast shouldn't create any DynamoDB table when I defined FeatureView with online=False.

## Current Behavior

Feast creates empty DynamoDB table when I defined FeatureView with online=False.

## Steps to reproduce

Define a feature store like this 

```yaml
project: example_feature_sotre

provider: aws

offline_store:
  type: spark
  spark_conf: {}

online_store:
  type: dynamodb
  region: us-east-1

entity_key_serialization_version: 2
```

Feature view def

```python
feature_view = FeatureView(
    name="abc_details_monthly",
    entities=[user_id],
    online=False,
    source=SparkSource(
      table="shcema.abc_details_monthly",
      name="abc_details_monthly",
      timestamp_field="event_date",,
      ttl=datetime.timedelta(days=27),
    # Schema definition
    schema=[
        Field(
            name="feature_1_1d",
            dtype=types.Int32,
            description=""
        )
    ]
)
```

### Specifications

- Version: 0.40.1
- Platform: Linux
- Subsystem:

## Possible Solution

Should distinguish list tables to keep of online store and offline store in this file.

https://github.com/feast-dev/feast/blob/cd87562df7f55dfe888bfbbd9a33b87670681040/sdk/python/feast/infra/passthrough_provider.py#L122
