### ISSUE TITLE
A CLI command to dump the actual configuration

### ISSUE THREAD

**Issue by dmartinol** [feast-dev/feast#4622]
**Is your feature request related to a problem? Please describe.**
Sometimes Feast applies default configurations when the user configuration is not completely provided.
To avoid misinterpretations, a `feast` CLI command could expose the actual configuration.

For example, if we provide the default configuration generated by `feast init`:
```yaml
project: foo
# By default, the registry is a file (but can be turned into a more scalable SQL-backed registry)
registry: data/registry.db
# The provider primarily specifies default offline / online stores & storing the registry in a given cloud
provider: local
online_store:
    type: sqlite
    path: data/online_store.db
entity_key_serialization_version: 2
# By default, no_auth for authentication and authorization, other possible values kubernetes and oidc. Refer the documentation for more details.
auth:
    type: no_auth
```
The actual configuration adds the offline config, which was not provided by the user:
```
> python
>>> from feast.feature_store import FeatureStore
>>> FeatureStore("foo/feature_repo").config
RepoConfig(project='foo', provider='local', registry_config='data/registry.db', online_config={'type': 'sqlite', 'path': 
'data/online_store.db'}, auth={'type': 'no_auth'}, offline_config='dask', batch_engine_config='local', feature_server=None, 
flags=None, repo_path=PosixPath('foo/feature_repo'), entity_key_serialization_version=2, coerce_tz_aware=True)
```

**Describe the solution you'd like**
Example of command to expose the actual configuration: `feast configuration`
Example of output:
```yaml
project: foo
registry: data/registry.db
provider: local
online_store:
    type: sqlite
    path: data/online_store.db
offline_store: 
    type: dask # Default config added by Feast
entity_key_serialization_version: 2
auth:
    type: no_auth
```

**Describe alternatives you've considered**
An SDK API to expose the same could be another option to access the actual config programmatically.
