### ISSUE TITLE
Feast Operator: Support Log Level Configuration in FeatureStore CR for Feature Services

### ISSUE THREAD

**Issue by redhatHameed** [feast-dev/feast#4810]
we need to add l og level configuration in FeatureStore CR, followed the requirements from https://github.com/feast-dev/feast/blob/master/sdk/python/feast/cli.py#L85,  only allow  values "debug", "info", "warning", "error", "critical".
```
spec:
  feastProject: test
  services:
    offlineStore:
      logLevel: debug
    onlineStore:
      logLevel: debug
    registry:
      local:
        logLevel: debug
```
optional, would add the following at service startup -

`--log-level DEBUG `

The `--log-level` parameter should be included in the Feast service deployment command only if it is explicitly configured in the  (CR) by the user.
If `logLevel` is not specified in the CR, the deployment command should not include the `--log-level` parameter.
