### ISSUE TITLE
RepoConfig cannot load its own write

### ISSUE THREAD

**Issue by heavenmarshal** [feast-dev/feast#4879]
## Expected Behavior 
The following code should run successfully
```python
from pathlib import Path
from feast import RepoConfig
from feast.repo_config import load_repo_config

config = RepoConfig(**{
    "project": "test",
    "registry": "./registry.db",
    "provider": "local",
    "online_store": {
        "type": "dynamodb",
        "region": "us-east-1",
    },
    "entity_key_serialization_version": 2,
})
config.write_to_path(Path("."))

load_repo_config(Path("."), Path("./feature_store.yaml"))

```
## Current Behavior
It raises exception:
```
File ~/Library/Python/3.9/lib/python/site-packages/feast/repo_config.py:600, in load_repo_config(repo_path, fs_yaml_file)
    598 raw_config = yaml.safe_load(os.path.expandvars(f.read()))
    599 try:
--> 600     c = RepoConfig(**raw_config)
    601     c.repo_path = repo_path
    602     return c

File ~/Library/Python/3.9/lib/python/site-packages/feast/repo_config.py:234, in RepoConfig.__init__(self, **data)
    232 self._registry = None
    233 if "registry" not in data:
--> 234     raise FeastRegistryNotSetError()
    235 self.registry_config = data["registry"]
    237 self._offline_store = None

```
## Steps to reproduce

see the code snippet

### Specifications

- Version: 0.42.0
- Platform: MacOS/linux
- Subsystem:

## Possible Solution
add `by_alias=True` at [this line](https://github.com/feast-dev/feast/blob/v0.42.0/sdk/python/feast/repo_config.py#L498)

**Comment by heavenmarshal** [comment]
the feature_store.yaml written by `config.write_to_path`:
```yaml
project: test
provider: local
registry_config: ./registry.db
online_config:
  type: dynamodb
  region: us-east-1
offline_config: file
batch_engine_config: local
entity_key_serialization_version: 2
```
