### ISSUE TITLE
Operator's Kubernetes Authz configuration causes an infinite loop & an ever growing RoleBinding

### ISSUE THREAD

**Issue by tchughesiv** [feast-dev/feast#5055]
## Expected Behavior 
The operator should successfully reconcile the CR and finish relatively quickly.

## Current Behavior
The operator goes into an infinite loop and the resulting RoleBinding's `subjects` array continues to grow in size.

## Steps to reproduce
```yaml
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: sample-kubernetes-auth
spec:
  authz:
    kubernetes:
      roles:
        - reader
        - writer
```

### Specifications

- Version: 0.45.0
- Platform: k8s / openshift
- Subsystem:
