### ISSUE TITLE
Snowflake CREATE TEMPORARY TABLE does not use schema

### ISSUE THREAD

**Issue by ryanjclark** [feast-dev/feast#5188]
## Expected Behavior 
I expect `schema` in Snowflake offline config to be used for temporary table creation.

## Current Behavior
Snowflake will fail because a schema is not used. This is the query failing on Snowflake:
```
CREATE TEMPORARY TABLE "feast_entity_df_uuid" AS (
    SELECT
        one,
        two as event_timestamp
    FROM "DB"."SCHEMA"."TABLE"
    LIMIT 10
)
```
This is the error.
```
Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
```

## Steps to reproduce
```
# feature_store.yml
offline_store:
    type: snowflake.offline
    account: acct
    user: user
    authenticator: externalbrowser
    role: MY_ROLE
    warehouse: MY_WH
    schema: SCHEMA
    database: DB
```
```
# repo.py
my_source = SnowflakeSource(
    name="my_source",
    database="DB",
    schema="SCHEMA",
    table="TABLE",
    timestamp_field="ts",
)
```
```
# query.py
store = FeatureStore(repo_path=".")
print(store.config) # prints correct config

entity_sql = f"""
    SELECT
        one,
        two as event_timestamp
    FROM "DB"."SCHEMA"."TABLE"
    LIMIT 10
"""

training_df = store.get_historical_features(
    entity_df=entity_sql,
    features=[
        "my_fv:feat",
    ],
).to_df()
```

### Specifications

- Version: 0.47
- Platform: Mac
- Subsystem:

## Possible Solution
Not sure why this is happening based on the code I see.
