### ISSUE TITLE
Memory leaks in feast core

### ISSUE THREAD

**Issue by pmjacinto** [feast-dev/feast#750]
## Expected Behavior 

Feast core memory usage should be stable.

## Current Behavior

I'm experiencing frequent restarts of the core service pod in GKE due to memory leaks.

The screenshots below are for an environment using v0.5.0, with a single ingestion job (the Job runs in Dataflow). I'm not setting any custom JVM parameters.

Memory usage measured by Prometheus & Node Exporter using `container_memory_working_set_bytes`

![image](https://user-images.githubusercontent.com/29306657/83119201-526c8080-a0c7-11ea-901d-ebbb9ca04f2b.png)

Feast batch serving seems ok.
![image](https://user-images.githubusercontent.com/29306657/83119464-a6776500-a0c7-11ea-82c3-f0f9f1f71baa.png)

Has anybody else experienced this?

## Steps to reproduce

Spin up feast deployment in GKE.

### Specifications

- Version: 0.5.0
- Platform: GKE
- Subsystem: Feast Core

**Comment by woop** [comment]
@pmjacinto I have not noticed this on our deployments of Feast Core. They are running quite reliably, but I'm not sure if our configuration is different somehow.

Your config is completely standard right? And you have no users except for a single feature set that is registered?

**Comment by pmjacinto** [comment]
Hey @woop 

Yes, no users and a single feature only.

We have some changes in our values file, but nothing that should affect memory. Added it below.

```
feast-core:
  image:
    repository: gcr.io/kf-feast/feast-core
    tag: 0.5.0
  service:
    type: ClusterIP
    http:
      nodePort: false
    grpc:
      nodePort: false
  ingress:
    http:
      enabled: true
      hosts:
      - #url
      auth:
        enabled: true
        authUrl: # auth url
    grpc:
      enabled: true
      hosts:
      - #url
      whitelist: #cidr
  resources:
    limits:
      cpu: 2
      memory: 2G
    requests:
      cpu: 100m
      memory: 500Mi
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  gcpServiceAccount:
    enabled: true
    existingSecret:
      name: feast-service-account
      key: credentials.json
  gcpProjectId: #proj
  logLevel: INFO
  application-generated.yaml:
    enabled: false
  application-secret.yaml:
    enabled: true
  application-override.yaml:
    feast:
      jobs:
        polling_interval_milliseconds: 60000
        job_update_timeout_seconds: 240
        active_runner: dataflow
        runners:
          - name: dataflow
            type: DataflowRunner
            options:
              region: europe-west4
              zone: europe-west4-b
              project: #proj
              network: default
              maxNumWorkers: 1
              autoscalingAlgorithm: THROUGHPUT_BASED
              usePublicIps: false
              workerMachineType: n1-standard-1
              subnetwork: # net
              tempLocation: #temp
              stagingLocation: #stg
              serviceAccount: #svc acc
              deadLetterTableSpec: #table
        metrics:
          enabled: true
          type: statsd
          host: # statsd
          port: 9125
      stream:
        type: kafka
        options:
          topic: feast-features
          bootstrapServers: # kafka
          replicationFactor: 1
          partitions: 1
```
