### ISSUE TITLE
Helm chart values-batch-serving.yaml incorrectly asks for dataset_id when it actually means dataset name

### ISSUE THREAD

**Issue by kunaldeo** [feast-dev/feast#995]
In the following file:
`https://github.com/feast-dev/feast/blob/master/infra/charts/feast/values-batch-serving.yaml`

```
stores:
      - name: historical
        type: BIGQUERY
        config:
          project_id: <google_project_id>
          dataset_id: <bigquery_dataset_id>
```
If you provide the actual dataset_id, which is in the format of project:dataset_name feast will not able to do ingestion and will timeout without any error.

```
Waiting for feature set to be ready for ingestion... 
TimeoutError: Timed out waiting for feature set to be ready.
```
Example case in the wild: [Stackoverflow issue](https://stackoverflow.com/questions/63689577/feast-feature-store-timeouterror-timed-out-waiting-for-feature-set-to-be-rea)

The chart is actually expecting a dataset name here not the dataset id. It should be renamed accordingly. The same is also referred by [feast quick start guide](https://docs.feast.dev/getting-started/deploying-feast/kubernetes) and lot of new users are getting stuck here.
